# TODO: Remove the following once the rules in the file is addressed
inherit_from:
  - .rubocop_todo.yml
# end TODO

MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  Max: 45 # TODO: set to 30

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

HashSyntax:
  Enabled: false # don't force 1.9 hash syntax

SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces (eg { :a => 1 })

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RescueModifier:
  Enabled: false

AssignmentInCondition:
  Enabled: false

WhileUntilModifier:
  Enabled: false

AlignParameters:
  Enabled: false # don't care if parameters are not aligned

ParenthesesAroundCondition:
  Enabled: false

DotPosition:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lambda:
  Enabled: false # don't require -> for single line lambdas

RedundantSelf:
  Enabled: false

RedundantReturn:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false # we allow spaces inside hash brackets

Documentation:
  Enabled: false # don't require documentation

Encoding:
  Enabled: false # don't require utf-8 encoding on every file

MethodCalledOnDoEndBlock:
  Enabled: true

SingleLineBlockParams:
  Enabled: false

Style/Next:
  Enabled: false # don't enforce next in loops over if/unless

Rails/ActionFilter:
  Enabled: false # Rails 4.0 check

FormatString:
  Enabled: false # we use % for i18n

Style/WordArray:
  Enabled: false # don't force usage of %w()

Metrics/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Max: 600

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
